[package]
name = "webpsan-test"
edition.workspace = true
version.workspace = true

publish = false

[features]
default = []
libwebp = ["dep:libwebp-sys"]

[dependencies]
libwebp-sys = { version = "0.9.4", optional = true }
log = "0.4.17"
thiserror = "1.0.40"
