name: test
on: [push]

defaults:
  run:
    shell: bash
jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    env:
      TEST_DATA_SSH_KEY: ${{ secrets.TEST_DATA_SSH_KEY }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: checkout test-data submodule
        continue-on-error: true
        if: ${{ env.TEST_DATA_SSH_KEY != '' }}
        env:
          SSH_KEY: ${{ env.TEST_DATA_SSH_KEY }}
        run: |
          eval `ssh-agent`
          ssh-add - <<< "${SSH_KEY}"
          git submodule update --init mp4san/tests/test-data

      - name: cache cargo output
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

      - name: cargo check
        run:  cargo check --verbose

      - name: cargo build
        run:  cargo build --verbose

      - name: cargo test -- --skip test_data
        run:  cargo test --verbose -- --skip test_data

      - name: cargo test test_data
        continue-on-error: true
        if: ${{ env.TEST_DATA_SSH_KEY != '' }}
        run:  cargo test --verbose test_data -- --show-output

      - name: cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ github.token }}

  format-check:
    name: format-check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: cargo fmt --check
        run:  cargo fmt --check
